### ISSUE TITLE
is it possible to create non invite login alongside Doorman?

### ISSUE THREAD

**Issue by KDA809** [clarkeash/doorman#28]
is it possible to create non invite login alongside Doorman?
basically i'm using doorman and user can only register to site using invite code supplied but i want user to be able to register without code also if they have no invite to use other features available on site is this possible with Doorman

**Comment by clarkeash** [comment]
I am not sure if this will work, but you could try **not** setting the invite code as required so instead of:

```php
$this->validate($request, [
    'email' => 'required|email|unique:users',
    'code' => 'required|doorman:email',
]);
```

do:

```php
$this->validate($request, [
    'email' => 'required|email|unique:users',
    'code' => 'doorman:email',
]);
```

and see what happens. (I am not currently in a position to try this myself)

As for limiting features based on if they have an invite code or not, you would have to write the logic yourself.
